### ISSUE TITLE
Создание БД

### ISSUE THREAD

**Issue by Gouzhurou** [Gouzhurou/animal-shelter-bot#3]
1. Создать init.sql файл с созданием таблицы user с полями (все поля NOT NULL):

- name VARCHAR(30) 
- surname VARCHAR(30) 
- email VARCHAR(30) 
- age INTEGER с проверкой на age > 0
- city VARCHAR(30)
- role ENUM или VARCHAR(10) (user or admin)

2. Создать docker-compose.yaml с поднятием базы postgresql типа такого:

```
version: '3.8'

services:
  app:
    image: docker.io/library/car-showroom:latest
    environment:
      - DB_USER=postgres
      - DB_NAME=CarShowroom
      - DB_PASSWORD=zeyis16
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CarShowroom
      - POSTGRES_PASSWORD=zeyis16
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
```

3. Протестить 

### Структура

```
animal-shelter-bot/
├── animal_shelter_bot/
│   ├── init.sql
│   └── docker-compose.yaml
...
```
